# Generated by Django 4.1 on 2022-11-27 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(blank=True, choices=[('1', '14.99/month'), ('2', '149.99/year')], default=('0', 'None'), max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_info', models.IntegerField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('amount_paid', models.IntegerField(default=0)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
