# Generated by Django 4.1 on 2022-11-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_choices',
            field=models.IntegerField(choices=[(1, '14.99/month'), (2, '149.99/year'), (0, 'unsubscribed')], default=0),
        ),
    ]
