# Generated by Django 4.1 on 2022-11-28 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_subscriptionplan_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='start_date',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_choices',
            field=models.CharField(choices=[('Free', 'Free'), ('14.99/month', '14.99/month'), ('149.99/year', '149.99/year')], default='Free', max_length=120),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usersubscription')),
            ],
        ),
    ]
