# Generated by Django 4.1 on 2022-11-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_subscriptionplan_subscription_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_choices',
            field=models.CharField(choices=[('14.99/month', '14.99/month'), ('Free', 'Free'), ('149.99/year', '149.99/year')], default='Free', max_length=120),
        ),
    ]
