# Generated by Django 4.1 on 2022-11-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_subscriptionplan_subscription_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='amount_paid',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_choices',
            field=models.CharField(choices=[('Free', 'Free'), ('149.99/year', '149.99/year'), ('14.99/month', '14.99/month')], default='Free', max_length=120),
        ),
    ]
