# Generated by Django 4.1 on 2022-11-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_subscriptionplan_subscription_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_choices',
            field=models.CharField(choices=[('Free', 'Free'), ('14.99/month', '14.99/month'), ('149.99/year', '149.99/year')], default='Free', max_length=120),
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
