# Generated by Django 4.1 on 2022-12-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_subscriptionplan_subscription_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='_next_payment',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_choices',
            field=models.CharField(choices=[('14.99/month', '14.99/month'), ('149.99/year', '149.99/year'), ('Free', 'Free')], default='Free', max_length=120),
        ),
    ]
