# Generated by Django 4.1 on 2022-12-01 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_subscriptionplan_subscription_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_choices',
            field=models.CharField(choices=[('Free', 'Free'), ('149.99/year', '149.99/year'), ('14.99/month', '14.99/month')], default='Free', max_length=120),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersubscriptions_paymenthistory', to='accounts.usersubscription')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paymenthistory',
            constraint=models.UniqueConstraint(fields=('payment_date', 'amount'), name='together'),
        ),
    ]
