# Generated by Django 4.1 on 2022-12-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_subscriptionplan_subscription_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='next_payment',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subscription_choices',
            field=models.CharField(choices=[('14.99/month', '14.99/month'), ('149.99/year', '149.99/year')], max_length=120, null=True),
        ),
    ]
