# Generated by Django 4.1 on 2022-11-26 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=120)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('postal_code', models.CharField(max_length=7)),
                ('phone_num', models.CharField(max_length=12)),
                ('images', models.ImageField(upload_to='studios')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('coach', models.CharField(max_length=120)),
                ('keywords', models.CharField(max_length=120)),
                ('capacity', models.IntegerField()),
                ('times', models.CharField(max_length=120)),
                ('enrolled', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('studio', models.ManyToManyField(related_name='studios_classes', to='studios.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('quantity', models.IntegerField()),
                ('studio', models.ManyToManyField(related_name='studios_amenity', to='studios.studio')),
            ],
        ),
    ]
