# Generated by Django 4.1 on 2022-12-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='frequency',
            field=models.IntegerField(choices=[(3, 'Monthly'), (1, 'Daily'), (2, 'Weekly'), (0, 'Once')], null=True),
        ),
    ]
