# Generated by Django 4.1 on 2022-11-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_alter_studio_lat_alter_studio_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='frequency',
            field=models.IntegerField(choices=[(3, 'Monthly'), (2, 'Weekly'), (1, 'Daily'), (0, 'Once')]),
        ),
    ]
