# Generated by Django 4.1 on 2022-11-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_alter_classes_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'Once'), (1, 'Daily'), (3, 'Monthly'), (2, 'Weekly')], null=True),
        ),
    ]
