# Generated by Django 4.1 on 2022-11-27 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0006_alter_classes_frequency_alter_classes_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='frequency',
            field=models.IntegerField(choices=[(2, 'Weekly'), (1, 'Daily'), (0, 'Once'), (3, 'Monthly')], null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
