# Generated by Django 4.1 on 2022-11-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0012_alter_classes_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='frequency',
            field=models.IntegerField(choices=[(3, 'Monthly'), (0, 'Once'), (1, 'Daily'), (2, 'Weekly')], null=True),
        ),
    ]
