# Generated by Django 4.1 on 2022-11-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0018_alter_classes_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Daily'), (0, 'Once'), (3, 'Monthly'), (2, 'Weekly')], null=True),
        ),
    ]
