# Generated by Django 4.1 on 2022-11-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0019_alter_classes_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'Once'), (3, 'Monthly'), (2, 'Weekly'), (1, 'Daily')], null=True),
        ),
    ]
