# Generated by Django 4.1 on 2022-12-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0030_alter_classes_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Daily'), (3, 'Monthly'), (2, 'Weekly'), (0, 'Once')], null=True),
        ),
    ]
