# Generated by Django 4.1 on 2022-12-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0038_alter_classes_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='frequency',
            field=models.IntegerField(choices=[(3, 'Monthly'), (2, 'Weekly'), (0, 'Once'), (1, 'Daily')], null=True),
        ),
    ]
