# Generated by Django 4.1 on 2022-12-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0041_alter_classes_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='frequency',
            field=models.IntegerField(choices=[(2, 'Weekly'), (1, 'Daily'), (0, 'Once'), (3, 'Monthly')], null=True),
        ),
    ]
